### ISSUE TITLE
[Bug] Grafana-agent must run in infrastructure nodes

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/airflow-kubernetes#144]
The platform connector, AKA grafana-agent consumes quite a lot of memory, sometimes leading to memory pressure and pod evictions in worker nodes (I've seen instances consuming up to 5GiB), it must run on top of infrastructure nodes.

**Comment by mukrishn** [comment]
Hypershift clusters are very much dependent on this grafana-agent as one place monitor of multiple hosted clusters and there won't be any infra node running on hosted clusters. Creating `infra` pool on hosted cluster is not an option as it would defeat the purpose of hypershift, so would it be nice to install them on `worker` node itself if there isn't any `infra` node in the cluster? or a dedicated node to run this agent in such case.

**Comment by rsevilla87** [comment]
In that case we should set a nodeAffinity rather than a nodeSelector @mukrishn , that shouldn't affect hypershift clusters.

```yaml
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: node-role.kubernetes.io/infra
            operator: Exists
```
